//! Every font in the game. GENERATED by `tools/gbafont.py` from
//! `assets-src/fonts.toml` -- edit that and run `make fonts`.
//!
//! The sheets themselves are wired into `assets.rs`.

// Each module exposes the same small API whether or not the game uses all of it.
#![allow(dead_code)]

fn lookup(charset: &[u8], fold: bool, blank: usize, ch: u8) -> usize {
    let ch = if fold { ch.to_ascii_uppercase() } else { ch };
    charset.iter().position(|&g| g == ch).unwrap_or(blank)
}

pub mod ui {
    //! font.ttf @8px, objects, 8x8 cell. Sheets: `gfx/fonts/ui.png`.

    /// Glyphs in sheet order: the index is the frame or tile number.
    pub const CHARSET: &[u8] = b" 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ:$+-./!?";
    /// Pixels from one glyph to the next.
    pub const ADVANCE: i32 = 6;
    pub const LINE_HEIGHT: i32 = 9;
    pub const CELL: (i32, i32) = (8, 8);

    // Frame offset of each variant: frame = VARIANT + index(ch).
    pub const NORMAL: usize = 0;
    pub const DIM: usize = 45;

    /// Glyph index for `ch`; anything not in the charset is blank.
    pub fn index(ch: u8) -> usize {
        super::lookup(CHARSET, true, 0, ch)
    }

    /// Pixel width of `text`.
    pub fn width(text: &[u8]) -> i32 {
        text.len() as i32 * ADVANCE
    }
}

pub mod digits {
    //! font.ttf @8px, objects, 8x8 cell. Sheets: `gfx/fonts/digits.png`.

    /// Glyphs in sheet order: the index is the frame or tile number.
    pub const CHARSET: &[u8] = b"0123456789+- ";
    /// Pixels from one glyph to the next.
    pub const ADVANCE: i32 = 6;
    pub const LINE_HEIGHT: i32 = 9;
    pub const CELL: (i32, i32) = (8, 8);

    // Frame offset of each variant: frame = VARIANT + index(ch).
    pub const NORMAL: usize = 0;
    pub const ALT: usize = 13;

    /// Glyph index for `ch`; anything not in the charset is blank.
    pub fn index(ch: u8) -> usize {
        super::lookup(CHARSET, false, 12, ch)
    }

    /// Pixel width of `text`.
    pub fn width(text: &[u8]) -> i32 {
        text.len() as i32 * ADVANCE
    }
}

pub mod text {
    //! font.ttf @8px, tiles, 8x8 cell. Sheets: `gfx/fonts/text_dark.png`, `gfx/fonts/text_dim.png`.

    /// Glyphs in sheet order: the index is the frame or tile number.
    pub const CHARSET: &[u8] = b" 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ:$+-./!?";
    /// Pixels from one glyph to the next.
    pub const ADVANCE: i32 = 6;
    pub const LINE_HEIGHT: i32 = 9;
    pub const CELL: (i32, i32) = (8, 8);

    /// Glyph index for `ch`; anything not in the charset is blank.
    pub fn index(ch: u8) -> usize {
        super::lookup(CHARSET, true, 0, ch)
    }

    /// Pixel width of `text`.
    pub fn width(text: &[u8]) -> i32 {
        text.len() as i32 * ADVANCE
    }
}
